# Site settings
title: Sora 的博客
description: 随便写点什么.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" 
url: "https://soraom.github.io"
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about me
contact: contact
privacy-policy: privacy-policy
permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: soraOM #github username
repo: soraom.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/soraom/soraom.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
